### ISSUE TITLE
Typescript: Throws error on options.map() in WrapperRadio

### ISSUE THREAD

**Issue by tayv** [tayv/Project-Bubblegum#10]
Problem:

- When the Type `options=string[] `get the following error on `options.map()` in `Controller` `render` prop:
  - `Type 'Element[]' is missing the following properties from type 'ReactElement<any, string | JSXElementConstructor<any>>': type, props, key`
- When the Type `options=JSX.Element` or `options=JSX.Element[]` then get the following error on `.map`
  - `Property 'map' does not exist on type 'Element'`

Intended Behavior:

- `options` is intended to be an array of strings passed from the parent (`quiz-template.tsx`) down to` WrapperRadio.tsx`
- WrapperRadio is then supposed to `options.map()` through the array and use it to render the atomic `RadioButton` components

Current Workaround:

- Set Type `options=any`

**Comment by asherccohen** [comment]
can you point me to a place in code where this happens?

Controller is meant to return only JSX, so maybe you're returning an array of strings.

**Comment by tayv** [comment]
This issue went stale. Closing it.
