### ISSUE TITLE
add-datepick-control branch: React Hook Form doesn't register input value in parent form component

### ISSUE THREAD

**Issue by tayv** [tayv/Project-Bubblegum#21]
**Problem:**

- Unable to turn `DatePick` into an RHF controlled component so its value can be submitted with the test form.

**More Details:**

- Clicking on the "Test Submit" (or "Get Value" button when set up with respective input name) at the bottom of the test form should print in the console values for all inputs in the form.
- Setting the value via rhf's `setValue()` only works at the parent level (`quiz-template.tsx`) and not if done in the child `DatePick` component. 
- Ideally `setValue()` would be done within the button's onClick used for selecting the calendar date in `DatePick` on line 199. However, this returns undefined in the test form.

**How the DatePick is intended to work:**

- A jsx calendar is placed within a Radix UI Accordion primitive so that the calendar only shows when it's open.
- The selected date is displayed in a readOnly text input that is styled to fit within the Accordion's header.
- Using date-fns library, the calendar defaults to the user's current date. 
- Each day in the calendar is a styled button that updates a state variable called selectedDay. selectedDay is then formatted using date-fns library and displayed in a readOnly text input.
- The readOnly text input's value should be submitted with the rest of the form.

**What I've tried:**

- Using Controller for the text input within DatePick
- Passing a defaultValue prop to the Controller. This works but I'm unable to change the value.

Links:

- See branch https://github.com/tayv/Project-Bubblegum/tree/add-datepick-control for some attempts in progress

**Comment by asherccohen** [comment]
where is an example of this happening?

**Comment by tayv** [comment]
I just refactored the DatePick component to have an atomic Calendar component that's nested inside the DatePick Accordion.

I also used the new Field component to try to make it controlled but still not working:

### Example:

https://user-images.githubusercontent.com/48400779/229329803-6a36bf79-bead-4c32-b5e7-5c3362fa099e.mov

### Here's how I call it using `Field` on `date-pick-article`:
https://github.com/tayv/Project-Bubblegum/blob/main/pages/docs/date-pick-article.tsx#L121-L150

```
  <Field name="datePickField" control={control} defaultValue="">
    <DatePick
     // name="datePickField"
      label="datePickField"
      startYearRange={1990}
      endYearRange={2030}
    />
    </Field>
```

### This is the new `DatePick` component (now a molecule)

This is the input field that I want to get the value from for the phone. It's intended to be `readOnly` so the user must set the date via the calendar.

https://github.com/tayv/Project-Bubblegum/blob/main/designSystem/molecules/DatePick.tsx#L65-L72 

```
...
 <input
    name={name}
    ref={ref}
    readOnly
    type="text"
    className="shrink w-full p-0 m-0 bg-transparent border-none focus:ring-0 text-black cursor-pointer"
    value={format(selectedDay, "MMM-dd-yyyy")}
  />
...

```

And here's where the atomic Calendar lives inside the Radix accordion:

https://github.com/tayv/Project-Bubblegum/blob/main/designSystem/molecules/DatePick.tsx#L79-L89

```
  <Accordion.Content className="data-[state=closed]:w-60 data-[state=open]:w-full">
    {/* Calendar */}
    <Calendar
      startYearRange={startYearRange}
      endYearRange={endYearRange}
      selectedDay={selectedDay}
      setShowCalendar={setShowCalendar}
      setSelectedDay={setSelectedDay}
      defaultDate={parsedDefaultValue}
    />
  </Accordion.Content>
```

And the atomic Calendar is here: https://github.com/tayv/Project-Bubblegum/blob/main/designSystem/atoms/Calendar.tsx

**Comment by tayv** [comment]
I haven't had a chance to apply your suggestions in https://github.com/tayv/Project-Bubblegum/discussions/48 so the Field component used here is still needs work.

**Comment by tayv** [comment]
Fixed the issue in the above PR. The problem was related to needing to pass an `onChange` prop to `DatePick` and then a handler down to `Calendar`
