### ISSUE TITLE
InitialRenderIssue: Checkbox with visibility condition must be clicked to take effect

### ISSUE THREAD

**Issue by tayv** [tayv/Project-Bubblegum#29]
https://user-images.githubusercontent.com/48400779/221391697-4f995597-d2a1-44ea-a0be-8a920e8be346.mov

**Problem:**

- On the Test Form page, the checkbox with a visibility condition that changes the wording and radio group requires the user to change the checkbox value before the condition will take effect.

**More Details:**

- Checkbox id: `visCheckbox`
- Radio Groups impacted by checkbox selection. id: `bikeBrandRadio`, id: `motoTeamRadio`

**How it's intended to work:**

- The form's default values are set using react hook form's `reset() `hook
- The checkbox with id: `visCheckbox` is intended to be selected by default
- The `bikeBrandRadio` radio group should be displayed
- Toggling the checkbox will switch the wording and phrasing of the radio group

**What I've Tried**

- I'm using rhf's `watch() `hook to monitor `visCheckbox`. When the input value changes it updates `fieldValues` object
- Render correct wording and radio group using JSX condition 
  -  _ie._ `fieldValues.visCheckbox ) ? Radio group A ... : Radio group B ... `

**Examples**

From _Pages > Form > test-forms.tsx_ showing default value object used by rhf's `reset()` hook inside a `useEffect` (so it sets values on page load)

```
// set up form default values
    const defaultValues = {
      // Text Input Section
      singleInput: "",
      // Text Area Section
      standardTextArea: "",
      largeTextArea: "",
      // Radio Input Section
      standardRadio: "mint",
      horizontalRadio: "no",
      buttonRadio: "orange-button",
      // Checkbox Input Section
      checkboxInput: true,
      // Select Input Section
      flatSelect: "third",
      groupSelect: "third",
      // Have visibility conditions
      visRacingRadio: "moto-gp",
 👉  visCheckbox: true,
      bikeBrandRadio: "suzuki",
      motoTeamRadio: "honda",
    }

    // Set up form default values with rhf 
 👉 useEffect(() => {
      reset({ ...defaultValues }) 
    }, [])

    const fieldValues = {
      // Text Input Section
      singleInput: getValues("singleInput"),
      // Radio Input Section
      standardRadio: getValues("standardRadio"),
      horizontalRadio: getValues("horizontalRadio"),
      buttonRadio: getValues("buttonRadio"),
      registerradio: watch("registerradio"),
      bikeBrandRadio: watch("bikeBrandRadio"),
      motoTeamRadio: watch("motoTeamRadio"),
      // Checkbox Input Section
      checkboxInput: watch("checkboxInput"), 
      // Select Input Section
      flatSelect: getValues("flatSelect"),
      groupSelect: getValues("groupSelect"),
      // Visibliity Conditions
      visRacingRadio: watch("visRacingRadio"),
  👉 visCheckbox: watch("visCheckbox")
    }
```

And this is the JSX visibility condition:

```
     { 
            <Section />
             ...

                // Set visibility of radio group based on prev checkbox answer
            👉  ( fieldValues.visCheckbox ) ?
                  <WrapperRadioGroup
                    name="bikeBrandRadio"
                    groupLabel="Pick your favorite brand"
                    tipText="You should only see this if checkbox is selected"
                    control={control}
                    style="standard"
                    defaultValue="yamaha"
                    options={ [
                      {value: "honda", label: "Honda"}, 
                      {value: "yamaha", label: "Yamaha"}, 
                      {value: "suzuki", label: "Suzuki"}, 
                      {value: "kawasaki", label: "Kawasaki"}
                    ] }
                  /> :
                    <WrapperRadioGroup
                      name="motoTeamRadio"
                      groupLabel="Pick your favorite racing team"
                      tipText="You should only see this if the checkbox is NOT selected"
                      control={control}
                      style="standard"
                      options={ [
                        {value: "yamaha", label: "Monster Energy Yamaha"}, 
                        {value: "honda", label: "Repsol Honda"}, 
                        {value: "ducati", label: "Factory Ducati"}, 
                        {value: "ferrari", label: "Ferrari"}
                      ] }
                    /> 
              }
            </Section>
          }
```

**Comment by asherccohen** [comment]
Quick tip: visibility of a field should't use external state, but the form's internal state.

https://github.com/tayv/Project-Bubblegum/blob/d6bb0080e4c859cf35718d2150cdd8d2523888b1/pages/forms/test-form.tsx#L115

For this RHF gives you useWatch. https://react-hook-form.com/api/usewatch/#main

This hook is like a tracker of the value of one (or more) fields and it returns its value.
It's really powerful for conditional logic.

Check out the rules though, it absolutely needs defaultValues!

**Comment by tayv** [comment]
Any opinions on using [watch()](https://react-hook-form.com/api/useform/watch/) vs [useWatch()](https://react-hook-form.com/api/usewatch/#main)?

I've been using `watch()` because it's a bit simpler to call (`watch("name")` instead of `useWatch({control, name: "name"})` and can just be destructured from `useForm()` 

Main benefit to `useWatch` seems to be a _potential_ performance boost in large forms?

> Behaves similarly to the watch API, however, this will isolate re-rendering at the custom hook level and _potentially_ result in better performance for your application.

**Comment by asherccohen** [comment]
useWatch is a bit more optimized since it's a hook.

I normally useWatch() since inevitably you'll switch to the Provider version of RHF.

Since values should be collected onSubmit, I'm not sure what is your desired outcome with this object?

    const fieldValues = {
      // Text Input Section
      singleInput: getValues("singleInput"),
      // Radio Input Section
      standardRadio: getValues("standardRadio"),
      horizontalRadio: getValues("horizontalRadio"),
      buttonRadio: getValues("buttonRadio"),
      registerradio: watch("registerradio"),
      bikeBrandRadio: watch("bikeBrandRadio"),
      motoTeamRadio: watch("motoTeamRadio"),
      // Checkbox Input Section
      checkboxInput: watch("checkboxInput"), 
      // Select Input Section
      flatSelect: getValues("flatSelect"),
      groupSelect: getValues("groupSelect"),
      // Visibliity Conditions
      visRacingRadio: watch("visRacingRadio"),
  👉 visCheckbox: watch("visCheckbox")
    }

Don' forget that since this is generated on every render it defeats the purpose of using watch.

**Comment by tayv** [comment]
Fixed with [PR 49](https://github.com/tayv/Project-Bubblegum/pull/49). The problem was with using `defaultChecked` in the Checkbox component when these are controlled components.
