### ISSUE TITLE
BUG: refactor-radio branch - Unable to select a previously chosen radio answes

### ISSUE THREAD

**Issue by tayv** [tayv/Project-Bubblegum#60]
Problem:

- Can select new radio buttons but not previously selected ones

Example:

https://github.com/tayv/Project-Bubblegum/assets/48400779/de58bd14-d1b2-4d6e-bf00-80e1511ee979

**Comment by tayv** [comment]
Not destructuring `name` and `defaultValue` from props changes behavior. It now requires two clicks to change an unselected value. Returning to a previously selected value only takes one click. 

```
// MAIN COMPONENT
const RadioGroup: FC<RadioGroupProps> = forwardRef<HTMLButtonElement, RadioGroupProps>(function setRadioRef(
  {
    type = "standard",
  //  name,
    options,
    //defaultValue,
   // value, // WARNING: DON'T USE THIS PROP. It causes defaulValue to be ignored
    className,
    hasError, // need to destructure to avoid React dom error
    ...props
  },
  ref
) { ... }
```

**Comment by tayv** [comment]
Possibly related to using a map to render the Items. Using hardcoded Items behaves as expected (ie. single click selection)

**Comment by tayv** [comment]
Given the problem seems related to map/rendering, I though the problem was with `key`. However moving the key from the parent div to the individual Item made no difference.

## Examples

### This works (hardcode/avoid using `map`):
```
return (
    <RadixRadioGroup.Root
      {...props as Omit<RadioGroupProps, 'onChange'>} // Needed to stop TS error on Root
      onValueChange={props.onChange}
      //defaultValue={defaultValue}
      className={classNames([
        "grid gap-2 my-2.5", // standard css styles go here. 
        radioGroupRootMap[type], // dynamic styles
        className, // one-off prop styles
      ])}
    >
 
      // HARDCODE ITEMS INSTEAD OF MAP
      <RadixRadioGroup.Item
        id={options[0].value}
        value={options[0].value}
        key={options[0].value}
        className={classNames([
          "data-[state=checked]:cursor-default",
          radioGroupItemMap[type], 
          className, 
        ])}
      >
        <RadixRadioGroup.Indicator 
          className={classNames([
            "",
            radioGroupIndicatorMap[type],
            className, 
          ])}
        >
          <div className="w-2.5 h-2.5 rounded-full bg-sky-400"></div> 
        </RadixRadioGroup.Indicator>
        <label
          htmlFor={options[0].value}
          className={classNames([
            "cursor-pointer",
            radioGroupLabelMap[type],
            className, 
          ])} 
        >
          {options[0].label}
        </label>
      </RadixRadioGroup.Item>

      ...  // Continue with hardcoded RadixRadioGroup.Items here 

    </RadixRadioGroup.Root>
  )
})
```

### This does not work:

https://github.com/tayv/Project-Bubblegum/blob/87533afbff939b684a18947e9ebb6fe8a31ad5e4/designSystem/molecules/RadioGroup.tsx#L46-L116

**Comment by asherccohen** [comment]
Do you have an update on this issue?

Keep in mind that sometimes you have to apply transformations to value and onChange in order to accommodate for differences in shapes between the Radix API and your intended use of the field.

I suggest fixing these outside of the Custom Form Component.

Another thing to notice is that you want to be using is "value".
React-hook-form always populates value on first render based on defaultValue, so it will always be there.

**Comment by tayv** [comment]
> Do you have an update on this issue?
I'm stuck and haven't made any more progress aside from getting it to work if I hardcode everything and set each item's value to a fixed string.

> Keep in mind that sometimes you have to apply transformations to value and onChange in order to accommodate for differences in shapes between the Radix API and your intended use of the field.

I'm having trouble understanding which transformations are needed. For example the Radix API shows Item's value should be a string. But I'm confused why  `value={index.toString()}` would work (_see Edit2 in post above_) but this doesn't: `value={option.value.toString()}` Plus the value of option.value should already be a string.

> I suggest fixing these outside of the Custom Form Component.
So in `Field`? I'm just not sure how to handle all the transformations in a central place if the requirements will end up varying by child input component? Or am I misunderstanding?

> Another thing to notice is that you want to be using is "value".
I realize now my code comment might be confusing. I meant that destructuring it seemed to cause problems but just passing it with the rest of the spread props to Root works still.

**Comment by asherccohen** [comment]
What's the type for your options prop?

Should be something like: 

{
id: string;
label: string;
}[]

So then you iterate it and assign "id" to the Item's "value" prop.

Basically radix components that are made of a root and an item (like here or in select) use a string to associate the selected value.

Check your Select and the implementation should be the same.

**Comment by tayv** [comment]
My options type is `  options: Array<{ value: string; label: string }>`

I use it like this inside Field:
```
...
<Field.Control>
    <SelectRadix
      placeholder="Select an option"
      itemOptions={[
        {
          value: "first",
          labelText: "firstText",
          separator: false,
        },
        {
          value: "second",
          labelText: "secondText",
          separator: true,
        },
        {
          value: "third",
          labelText: "thirdText",
          separator: false,
        },
        {
          value: "fourth",
          labelText: "fourthText",
          separator: true,
        },
      ]}
    />
  </Field.Control>
...
```

The properties are strings so I'm expecting when I map over them and set a RadixRadioGroup.Item's value to equal the option.value that it should work. 

Currently my best guess is maybe it's something nuanced with how react renders items when mapping over objects??

**Comment by tayv** [comment]
Put together a codesandbox to try and isolate the problem. Seems that the hardcoded string solution doesn't work in the sandbox.

https://codesandbox.io/p/sandbox/project-template-sbvp5j?file=%2Fcomponents%2Fmolecules%2FRadioGroupHardcoded.tsx%3A1%2C1

**Comment by tayv** [comment]
Needs some more testing but think I've solved this 🤞

Looks like problem was from not destructuring `onChange` which is probably sending two values to Controller since Radix has its own `onValueChange`.

Fix:
1. Destructure onChange
2. Pass it to onValueChange: `onValueChange={onChange}`
